DATASET:
  NAME: "TCGA_BRCA"
  URL: "https://github.com/pykale/data/raw/main/multiomics/TCGA_BRCA.zip"
  NUM_MODALITIES: 3
  NUM_CLASSES: 5

SOLVER:
  MAX_EPOCHS_PRETRAIN: 5 # For quick testing
  MAX_EPOCHS: 10  # For quick testing

MODEL:
  EDGE_PER_NODE: 10
  GCN_HIDDEN_DIM: [400, 400, 200]
